export default function DotsSvg() {
  return (
    <svg
      width="60"
      height="10"
      viewBox="0 0 60 10"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <circle
        cx="5"
        cy="5"
        r="3.5"
        stroke="black"
        strokeWidth="1"
        fill="none"
      />
      <circle
        cx="15"
        cy="5"
        r="3.5"
        stroke="black"
        strokeWidth="1"
        fill="none"
      />
      <circle
        cx="25"
        cy="5"
        r="3.5"
        stroke="black"
        strokeWidth="1"
        fill="none"
      />
      <circle
        cx="35"
        cy="5"
        r="3.5"
        stroke="black"
        strokeWidth="1"
        fill="none"
      />
      <circle
        cx="45"
        cy="5"
        r="3.5"
        stroke="black"
        strokeWidth="1"
        fill="none"
      />
      <circle
        cx="55"
        cy="5"
        r="3.5"
        stroke="black"
        strokeWidth="1"
        fill="none"
      />
    </svg>
  );
}
